package ru.valera.domain.comment;

import java.util.Objects;

public class CommentId {

    private final Long value;

    public Long getValue() {
        return value;
    }

    private CommentId(Long value) {
        this.value = Objects.requireNonNull(value, "Comment id cannot be null");
        if (value <= 0) {
            throw new IllegalArgumentException("Comment id must be positive");
        }
    }

    public static CommentId of(Long value) {
        return new CommentId(value);
    }

    public static CommentId createNew() {
        throw new UnsupportedOperationException(
                "New comment id should be generated by database");
    }
}
