package ru.valera.domain.post;

import java.util.Objects;

public class PostId {

    private final Long value;

    private PostId(Long value) {
        this.value = Objects.requireNonNull(value, "Post id cannot be null");
        if (value <= 0) {
            throw new IllegalArgumentException("Post id must be positive");
        }
    }

    public static PostId of(Long value) {
        return new PostId(value);
    }

    public static PostId createNew() {
        throw new UnsupportedOperationException(
                "New post id should be generated by database");
    }

    public Long getValue() {
        return value;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        PostId postId = (PostId) o;
        return value.equals(postId.value);
    }

    @Override
    public int hashCode() {
        return value.hashCode();
    }

    @Override
    public String toString() {
        return "PostId{" + value + "}";
    }
}
