package ru.valera.domain.tag;

import java.util.Objects;

public class TagId {

    private final Long value;

    private TagId(Long value) {

        this.value = Objects.requireNonNull(value, "Post id cannot be null");
        if (value <= 0) {
            throw new IllegalArgumentException("Post id must be positive");
        }
    }

    public static TagId of(Long value) {
        return new TagId(value);
    }

    public static TagId createNew() {
        throw new UnsupportedOperationException(
                "New post id should be generated by database");
    }
}
